/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as QcRouteImport } from './routes/qc'
import { Route as JobJobIdRouteImport } from './routes/job.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdRoute = JobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/prompts': typeof PromptsRoute
  '/qc': typeof QcRoute
  '/job/$jobId': typeof JobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/prompts': typeof PromptsRoute
  '/qc': typeof QcRoute
  '/job/$jobId': typeof JobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/prompts': typeof PromptsRoute
  '/qc': typeof QcRoute
  '/job/$jobId': typeof JobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ingest' | '/prompts' | '/qc' | '/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingest' | '/prompts' | '/qc' | '/job/$jobId'
  id: '__root__' | '/' | '/ingest' | '/prompts' | '/qc' | '/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngestRoute: typeof IngestRoute
  PromptsRoute: typeof PromptsRoute
  QcRoute: typeof QcRoute
  JobJobIdRoute: typeof JobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId': {
      id: '/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/job/$jobId'
      preLoaderRoute: typeof JobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngestRoute: IngestRoute,
  PromptsRoute: PromptsRoute,
  QcRoute: QcRoute,
  JobJobIdRoute: JobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
